allowBuilds:
  '@firebase/util': set this to true or false
  bcrypt: set this to true or false
  canvas: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  puppeteer: set this to true or false
